### ISSUE TITLE
"Illegal reflective access" warning should be addressed

### ISSUE THREAD

**Issue by mschechter-bellese** [spotify/fmt-maven-plugin#106]
**Describe the bug**
Version 2.11 of the Maven plugin (available on Maven Central) generates the following working during formatting:

```
09:24:58.285 [INFO] --- fmt-maven-plugin:2.11:format (default) @ xxxxx ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.googlejavaformat.java.JavacTokens$CommentSavingTokenizer (file:/Users/xxxx/.m2/repository/com/google/googlejavaformat/google-java-format/1.10.0/google-java-format-1.10.0.jar) to field com.sun.tools.javac.parser.JavaTokenizer.reader
WARNING: Please consider reporting this to the maintainers of com.google.googlejavaformat.java.JavacTokens$CommentSavingTokenizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**To Reproduce**
Execute the `format` goal

**Expected behavior**
The warning should not occur

**Additional context**
I have reverted to the 2.10 plugin release, and the issue no longer occurs. This is a valid workaround for my team, so we're not blocked. You're still using this version on `master`, there's still a potential issue in subsequent releases.

I've also created an [issue](https://github.com/google/google-java-format/issues/622) in the `google-java-format` project, as this is most likely in their code.

**Comment by youngm** [comment]
So, those arguments certainly work. However, it would be nice if we eventually don't not have to add them.

**Comment by klaraward** [comment]
See also #99

**Comment by danielnorberg** [comment]
These warnings are still issued for JDK 9  to 15, despite https://github.com/spotify/fmt-maven-plugin/pull/140

**Comment by danielnorberg** [comment]
Closed by https://github.com/spotify/fmt-maven-plugin/pull/150
