### ISSUE TITLE
Support forking of plugin

### ISSUE THREAD

**Issue by klaraward** [spotify/fmt-maven-plugin#127]
Support forking of the plugin to be able to set jvm args needed to run with Java 16+.

After doing so, also remove the args in `.mvn/jvm.config` and in `<argLine>` introduced in #125

**Comment by Stephan202** [comment]
@klaraward will this be an optional feature? I'm asking because our builds have suitable args in `.mvn/jvm.config` for [other reasons](https://errorprone.info/docs/installation) anyway, so we'd rather not unnecessarily pay for the overhead of forking the JVM.

**Comment by klaraward** [comment]
Yes, forking will definitely be optional.

**Comment by klaraward** [comment]
I plan to work on this the coming days.

**Comment by danielnorberg** [comment]
Resolved by https://github.com/spotify/fmt-maven-plugin/pull/140

**Comment by norrisjeremy** [comment]
Can this be adjusted to always add the `--add-exports` & `--add-opens` statements when `forkMode` is set to `always`?
This would allow users a way to remove the `An illegal reflective access operation has occurred` warnings that are seen when using Java < 16.

**Comment by danielnorberg** [comment]
@norrisjeremy I reopened https://github.com/spotify/fmt-maven-plugin/issues/106 to continue the discussion on whether and how to eliminate these warnings on Java < 16.
