### ISSUE TITLE
Doesn't work with Java 21

### ISSUE THREAD

**Issue by duncanmak** [spotify/fmt-maven-plugin#178]
**Describe the bug**
The current release, 2.2.0, doesn't work with Java 21.

**Additional context**

I think other plugins have fixed the same issue already:
https://github.com/palantir/palantir-java-format/pull/909

**Comment by adrian-marcu** [comment]
Is someone going to contribute to update to work with Java version 21?

**Comment by spfeiffer-iem** [comment]
Will 2.21 be published to Maven Central, too?

Thank you very much,
Stefan

**Comment by caesar-ralf** [comment]
Yes, it's already there: https://mvnrepository.com/artifact/com.spotify.fmt/fmt-maven-plugin/2.21.1
