### ISSUE TITLE
2.22.0 Version Not Found

### ISSUE THREAD

**Issue by brenoepics** [spotify/fmt-maven-plugin#186]
**Describe the bug**
[The latest release version](https://github.com/spotify/fmt-maven-plugin/releases/tag/2.22.0) cannot be found in maven central, but 2.21.1 can.

**To Reproduce**

```xml
<plugin>
    <groupId>com.spotify.fmt</groupId>
    <artifactId>fmt-maven-plugin</artifactId>
    <version>2.22.0</version>
    <executions>
        <execution>
            <goals>
                <goal>format</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Additional context**

```
Plugin com.spotify.fmt:fmt-maven-plugin:2.22.0 or one of its dependencies could not be resolved: The following artifacts could not be resolved: com.spotify.fmt:fmt-maven-plugin:jar:2.22.0 (absent): com.spotify.fmt:fmt-maven-plugin:jar:2.22.0 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
```

**Comment by caesar-ralf** [comment]
It was released yesterday @brenoepics. It takes more than a day to be publicly available. Please check later today or tomorrow

**Comment by vladimirconev** [comment]
> It was released yesterday @brenoepics. It takes more than a day to be publicly available. Please check later today or tomorrow

It seems like it is still not resolved and I am still facing this issue. Please note that with previous versions up to v2.21.1 everything was super smooth. :) 

Thanks x10

**Comment by brenoepics** [comment]
@vladimirconev I think I know what is the issue, they published on maven as 2.22 and not 2.22.0 (but Github Release is 2.22.0)
just a little mistake.
![image](https://github.com/spotify/fmt-maven-plugin/assets/59066707/366a6088-8d68-47f0-a49e-7921bf01a825)
https://central.sonatype.com/artifact/com.spotify.fmt/fmt-maven-plugin

**Comment by vladimirconev** [comment]
@brenoepics thanks for reaching out. Please note that I did tried both options and could not resolve the initially reported issue 
![fmt-mvn-plugin_v22 2](https://github.com/spotify/fmt-maven-plugin/assets/11627839/16ef0faf-e3a2-4d96-9868-94e7de067403)

**Comment by brenoepics** [comment]
Hmm, yeah, I just moved from the plugin to github actions but tried again now with 2.22 instead of 2.22.0 and got the same error.
I took a look at 
https://repo.maven.apache.org/maven2/com/spotify/fmt/fmt-maven-plugin/ 
https://repo1.maven.org/maven2/com/spotify/fmt/fmt-maven-plugin/
and there is no 2.22.x release. 
![image](https://github.com/spotify/fmt-maven-plugin/assets/59066707/f778bf77-09e0-4cb0-8331-348f5550eb93)

but the file is there if you open https://repo.maven.apache.org/maven2/com/spotify/fmt/fmt-maven-plugin/2.22/
![image](https://github.com/spotify/fmt-maven-plugin/assets/59066707/80747824-55e8-4170-856f-29f8b0f739b2)

Something seems to be wrong @caesar-ralf

**Comment by brenoepics** [comment]
![image](https://github.com/spotify/fmt-maven-plugin/assets/59066707/793dfaff-5764-4487-b92e-995e94f28649)
Adding querystring I can see it, something cache related then.

**Comment by brenoepics** [comment]
@vladimirconev try to open `.m2\repository\com` and delete `spotify` then try again, it worked for me.
![image](https://github.com/spotify/fmt-maven-plugin/assets/59066707/c043ece3-afc0-4419-860c-f852fe93d766)

**Comment by brenoepics** [comment]
And yeah, 2.22.0 will not be found.

**Comment by caesar-ralf** [comment]
> @vladimirconev I think I know what is the issue, they published on maven as 2.22 and not 2.22.0 (but Github Release is 2.22.0) just a little mistake. ![image](https://private-user-images.githubusercontent.com/59066707/298293911-366a6088-8d68-47f0-a49e-7921bf01a825.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTQ1MjAsIm5iZiI6MTcwNTkxNDIyMCwicGF0aCI6Ii81OTA2NjcwNy8yOTgyOTM5MTEtMzY2YTYwODgtOGQ2OC00N2YwLWE0OWUtNzkyMWJmMDFhODI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDA5MDM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3MWNlYjc3MDc1YjAzZDQwYjRhZWIzZDBhM2E2M2Q0NDIxY2VmZWEwN2Q0NjA1ZjM3MWFmMTQ1ZGIyNTE4M2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ScAK_DoBKOap2Mm7ggOPeVFVQWkYUJn_yIkicvZcI9c) https://central.sonatype.com/artifact/com.spotify.fmt/fmt-maven-plugin

It's not a mistake. We are following the pattern that was set before we took over the library, which doesn't contain patch version number. We might change it in the future because the pattern is confusing.

The version in mvn repository is `2.22`: https://mvnrepository.com/artifact/com.spotify.fmt/fmt-maven-plugin/2.22
`2.22.0` is only the git tag: https://github.com/spotify/fmt-maven-plugin/releases/tag/2.22.0

**Comment by vladimirconev** [comment]
@caesar-ralf  thanks for your reply but unfortunately it is still NOK (not quite sure on the root cause). Please check  the uploaded gif and let me know whether we (cc: @brenoepics ) are doing something wrong. Specifying version 2.22 is not working. 

Thanks x10 and I do hope that  we'll be able to find the root cause.   
As per removing spotify folder from .m2/repository @brenoepics  => Please note that it might solve my issue locally but I am afraid I won't be able to do that on the instance where our Jenkins build server is.

**Comment by caesar-ralf** [comment]
> @caesar-ralf thanks for your reply but unfortunately it is still NOK (not quite sure on the root cause). Please check the uploaded gif and let me know whether we (cc: @brenoepics ) are doing something wrong. Specifying version 2.22 is not working.
> 
> Thanks x10 and I do hope that we'll be able to find the root cause. As per removing spotify folder from .m2/repository @brenoepics => Please note that it might solve my issue locally but I am afraid I won't be able to do that on the instance where our Jenkins build server is.

Have you tried to remove the cache from your jenkins instance? The release works as expected for in our jenkins instance, just having changed the version to `2.22`.

I will try to replicate your problem. I checked your gif. I would hav to check your whole plugin definition, but changing the version to 2.22 should be enough

**Comment by caesar-ralf** [comment]
Released a version `2.22.1` that's exactly like `2.22`, no aditions. It should arrive in mvn central either today or tomorrow. You can try with that version instead when it comes

**Comment by vladimirconev** [comment]
@caesar-ralf  Just in case you want to verify on your own (to reproduce the issue), following repositories are using fmt maven plugin:

- https://github.com/vladimirconev/testcontainers-sandbox 
- https://github.com/vladimirconev/docs-manager 

Once available in maven central v2.22.1 , I'll give it a try and provide feedback. 
Thanks

**Comment by vladimirconev** [comment]
@caesar-ralf  using version 2.22.1 works like charm. 
![fmt_v22_2_1](https://github.com/spotify/fmt-maven-plugin/assets/11627839/b77b8f2b-0090-4f8b-8d2f-fb1db85c4f35)
Not quite sure on the root cause but providing a new release with no additions seems to work just fine. 
Please @brenoepics  check it out and let us know. 

Thanks x10 and Happy Coding!

**Comment by brenoepics** [comment]
Working fine here too!
