### ISSUE TITLE
Different results from different tools using same style guide

### ISSUE THREAD

**Issue by PramodForce** [spotify/fmt-maven-plugin#21]
The code format results from the Intellij plugin https://plugins.jetbrains.com/plugin/8527-google-java-format is different from the results of this maven plugin.

**Comment by malaporte** [comment]
Care to elaborate on the differences?

**Comment by PramodForce** [comment]
The difference that I am seeing is in the import order and inner class positioning. A few specific examples :

1. The IJ (IntelliJ) plugin places javax.persistence.* imports above java.* imports. It is the opposite for FMP(fmt-maven-plugin).
2. The IJ plugin places java.* classes at the end of the imports list.
3. An inner enum class which was near the top of the class gets repositioned to the end of the class by the IJ plugin. That positioning is unaffected in FMP.

**Comment by aaime** [comment]
Known issue at the google-java-format level, see:
* https://github.com/google/google-java-format/issues/94
* https://github.com/google/google-java-format/issues/236

Basically it seems one has to tweak the IntelliJ code style when it comes to import organization, as that might still be under IntelliJ control

**Comment by Karakaz** [comment]
For me this is happening with annotations:
fmt-maven-plugin
```
@ExtendWith(SpringExtension.class)
@ContextConfiguration(
  classes = {DbConfig.class},
  loader = AnnotationConfigContextLoader.class
)
@Transactional
public class TableRepositoryLearningTest {
```

IntelliJ
```
@ExtendWith(SpringExtension.class)
@ContextConfiguration(
    classes = {DbConfig.class},
    loader = AnnotationConfigContextLoader.class)
@Transactional
public class TableRepositoryLearningTest {
```

**Comment by kavukcutolga** [comment]
Same here 
**maven**
`@Controller
public class BasicSpringMvcController {

  @Inject Aclassse class;

  @RequestMapping(value = "/", method = RequestMethod.GET)
  public String prepareView(Model model, HttpServletRequest request)
      throws NoSecurityContextAvailableException, JsonProcessingException {
    ObjectMapper objectMapper = new ObjectMapper();
    Aclassse context = class.createContext(request, null);
    String valueAsString = objectMapper.writeValueAsString(context);
    model.addAttribute("msg", valueAsString);
    return valueAsString;
  }
}
`
**intellij with intellij google style format** 
@Controller
public class BasicSpringMvcController {

  @Inject
  Aclass class;

  @RequestMapping(value = "/", method = RequestMethod.GET)
   public String prepareView(Model model, HttpServletRequest request)
      throws NoSecurityContextAvailableException, JsonProcessingException {
    ObjectMapper objectMapper = new ObjectMapper();
    Aclassse context = class.createContext(request, null);
    String valueAsString = objectMapper.writeValueAsString(context);
    model.addAttribute("msg", valueAsString);
    return valueAsString;
  }
}


Any suggestiom

**Comment by malaporte** [comment]
Did you try running the Google Formatter directly through the command line to see what "version" you get? If the command line one gives the same result as the Maven plugin, you'll know that the issue is actually in the IntelliJ integration, and you should submit a bug there ...

**Comment by klaraward** [comment]
Going to assume this is solved now
