### ISSUE TITLE
Add a way to figure out why a file is not formatted

### ISSUE THREAD

**Issue by aaime** [spotify/fmt-maven-plugin#29]
Right now the check fails with an indication that the file is not properly formatted, but does not specify how or why. I have observed difficulties in IDE integration, generating non compliant files despite the google formatting plugins being installed (and besides that, not everybody uses IntelliJ or Eclipse).

Looking at the check code, it simply does a text comparison between its formatted output and the file.
Maybe using something like https://github.com/google/diff-match-patch would be useful in identifying the sections that are at fault, along with an option to control its usage.

**Comment by sormuras** [comment]
Using "google-java-format" you don't (need to) care about the "why". Just let the formatter do its job and see the diff in your tool of choice.

**Comment by malaporte** [comment]
Exact - the whole point of the Google formatter is that you don't have to configure it.

Regarding outputting a diff when non-compliant files are found, I guess this might help a bit diagnosing issues when using IDE formatters; I'll gladly accept a PR adding this 😁
