### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by mithuns** [spotify/fmt-maven-plugin#32]
Is there a way to force what kind of line endings this will format the code into ? 
If not, is that something that can be added. 
I think if I am using this plugin for all the formatting, having consistent line-endings is something that would be vital to the formatting task. 
I know there are ways to enforce line endings at git , and at user level configuration, but if this plugin supports that, it would be one stop solution to all my formatting needs.

**Comment by GuiSim** [comment]
I've never looked at which file ending is used. I suspect it probably always uses UNIX line endings? I don't have access to a PC to test if the line endings change depending on the platform.

Please give it a try, the line endings should be consistent no matter the platform.
They will not however be configurable.

**Comment by bencaradocdavies** [comment]
It would be great to have an option to to format/check that line endings are native. Without this option, fmt-maven-plugin running on Travis CI does not detect GitHub pull requests that attempt to change line endings from LF to CRLF, typically from misconfigured git clients.

**Comment by mithuns** [comment]
Yeah, just verified , it does not do anything towards line-endings.

**Comment by klaraward** [comment]
This would be an issue for the underlying google-java-format
