### ISSUE TITLE
Misleading message

### ISSUE THREAD

**Issue by mikaelstaldal** [spotify/fmt-maven-plugin#37]
When running `check` and finding misformatted code, it tells you to run `mvn fmt:format`. However, that does not work, I have to run `mvn com.coveo:fmt-maven-plugin:format`.

```
[ERROR] No plugin found for prefix 'fmt' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories
```

**Comment by loosebazooka** [comment]
Do you not have the plugin specified in the pom?

**Comment by mikaelstaldal** [comment]
I have this in my pom:
```
      <plugin>
        <groupId>com.coveo</groupId>
        <artifactId>fmt-maven-plugin</artifactId>
        <version>2.5.1</version>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

**Comment by wlfshmn** [comment]
I too ran across this, it's a simple literal to change in the check mojo to alter. To get the documkented behaviour to work, the user would also need to add the following to their settings.xml
```
<pluginGroups>
  <pluginGroup>com.coveo</pluginGroup>
</pluginGroups>
```
Without it maven will only search a few preset groups for plugins, by default I believe the apache maven and codehaus namespaces.

I personally feel it is better for the plugin to output working, if less pretty, suggestions by default, as the gain of the more complicated configuration doesn't seem worth it to me.

**Comment by TobiX** [comment]
Remark: If the plugin is listed in `<pluginManagement>`, the short form also works.

**Comment by klaraward** [comment]
I believe this is fixed, feel free to reopen if not

**Comment by firatkucuk** [comment]
I get this error on a parent pom. If I run formatting command as if `mvn fmt:format` then I get the exactly the same error. But If the command is `mvn com.spotify.fmt:fmt-maven-plugin:format` then it works.
