### ISSUE TITLE
Different imports sections formatting between 2.9.1 and 2.10.0

### ISSUE THREAD

**Issue by ava1ar** [spotify/fmt-maven-plugin#70]
**Describe the bug**
Imports sections formatted differently by plugin of versions 2.9.1 and 2.10.0

**To Reproduce**
- Get some Java class with different kind of imports (from com, net, org, java, etc)
- Reformat code with plugin version 2.9.1
- Reformat code with plugin version 2.10.0
Compare the results

**Expected behavior**
Both plugins expected to produce exactly same output, but they are not

**Additional context**
This is kind of diff I am getting with 2.10.0 applied on top of 2.9.1:

```
@@ -9,11 +9,13 @@
 import com.mlp.raptor.wiring.Transport;
 import com.mlp.raptor.wiring.TransportManager;
 import com.mlp.raptor.wiring.session.SessionManager;
-import java.util.concurrent.TimeUnit;
+
 import org.junit.jupiter.api.BeforeAll;
 import org.junit.jupiter.api.Disabled;
 import org.junit.jupiter.api.Test;

+import java.util.concurrent.TimeUnit;
+
```
Looks like non-static imports are not grouped and separated by empty line. Not sure if this is expected change, since there were no changes regarding this in `google-java-format` between versions 1.7 and 1.8.

**Comment by klaraward** [comment]
Closing this old issue we can't do anything about
