### ISSUE TITLE
Can we get a new release please?

### ISSUE THREAD

**Issue by timmolter** [spotify/fmt-maven-plugin#97]
I'm especially interested in this feature: https://github.com/coveooss/fmt-maven-plugin/pull/69

**Comment by ava1ar** [comment]
google-java-format version 1.9 should be included as well!

**Comment by bmarwell** [comment]
Oh, please let Spotify fork it! This plugin is so great, it should be organizational managed... 🙏🏻

**Comment by klaraward** [comment]
Spotify has now release com.spotify.fmt:fmt-maven-plugin:2.14
