### ISSUE TITLE
Remove wildcard imports

### ISSUE THREAD

**Issue by maheshkumargp** [spotify/fmt-maven-plugin#98]
Please add a feature to remove wildcard imports

for ex : 
import org.apache.commons.lang3.*;

replace this with 

import org.apache.commons.lang3.StringUtils;

**Comment by ava1ar** [comment]
@maheshkumargp this plugin doesn't do any formatting my itself - all it does it calls https://github.com/google/google-java-format with provided configuration. So, if you want to request changes to the formatting logic itself you should request this from google-java-format, not this project.
