### ISSUE TITLE
Breaks with JDK 16

### ISSUE THREAD

**Issue by bitzl** [spotify/fmt-maven-plugin#99]
**Describe the bug**
Using this plugin with JDK16 fails because `com.sun.tools.javac.parser.Tokens$TokenKind` is not accessible anymore:

```
Error:  Failed to execute goal com.coveo:fmt-maven-plugin:2.10:format (default) on project framework: Execution default of goal com.coveo:fmt-maven-plugin:2.10:format failed: An API incompatibility was encountered while executing com.coveo:fmt-maven-plugin:2.10:format: java.lang.IllegalAccessError: class com.google.googlejavaformat.java.JavaInput (in unnamed module @0x47c7a9e5) cannot access class com.sun.tools.javac.parser.Tokens$TokenKind (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.parser to unnamed module @0x47c7a9e5
```

**To Reproduce**
Run a Maven build using this plugin with OpenJDK 16.

**Expected behavior**
The code get formatted without an error.

**Additional context**
Builds with OpenJDK 15 work fine. Cause for this error are likely changes for [JEP 396: Strongly Encapsulate JDK Internals by Default](https://openjdk.java.net/jeps/396).

Corresponding Ticket for Google Java Format: https://github.com/google/google-java-format/issues/538

**Comment by famaridon** [comment]
#100 will fix it just need a release.

and add documentation because https://github.com/google/google-java-format/releases/tag/v1.10.0 need more java flags due to JEP 396: Strongly Encapsulate JDK Internals by Default

```

**Comment by klaraward** [comment]
#100 is merged and version 2.11 is released, but the problem with the options still prevail.

**Comment by msche** [comment]
Upgrading `google-java-format` to version `1.11.0` might fix this issue as [https://github.com/google/google-java-format/issues/538 ](Running on Java 16 fails) seems to be fixed in that release.

**Comment by klaraward** [comment]
> Upgrading `google-java-format` to version `1.11.0` might fix this issue as [https://github.com/[google/google-java-format/issues/538](https://github.com/google/google-java-format/issues/538) ](Running on Java 16 fails) seems to be fixed in that release.

Is it 1.10.0 - https://github.com/coveooss/fmt-maven-plugin/pull/100
or 1.11.0 -  https://github.com/coveooss/fmt-maven-plugin/pull/108
that is needed?

**Comment by klaraward** [comment]
I would say that 1.11.0 of the google-java-format does not help with the required commandline options, but it has other improvments.

**Comment by msche** [comment]
I was referring to 1.11.0

**Comment by malaporte** [comment]
I just release 2.12 which uses the latest Google Java Format version, but as mentioned above you still need to pass all the annoying options to Maven for it to work.

I started a branch to experiment with running the formatter in a child process, but as of now I have yet to figure out how to extract the right class path from the class loader that Maven is using (using the "all deps" version of Google Java Format would fix the problem, but it's not available on Maven meh).

**Comment by Stephan202** [comment]
@malaporte if you're successful with the fork approach, can you please make this an optional feature? Forking does have some performance impact, and some users will have instead solved the problem by adding the aforementioned flags to `.mvn/jvm.config`.

**Comment by malaporte** [comment]
Oh definitively - I was intending on doing that only for Java >= 16, and if possible check for the presence of the required flag to see if running in-process is an option.

**Comment by klaraward** [comment]
Any update on this @malaporte ?

**Comment by mattnelson** [comment]
> using the "all deps" version of Google Java Format would fix the problem, but it's not available on Maven

I'm seeing is there now.
https://repo1.maven.org/maven2/com/google/googlejavaformat/google-java-format/1.13.0/

**Comment by klaraward** [comment]
@malaporte Have you looked more into this?

**Comment by stanislavb** [comment]
I solved this by using instructions in README: https://github.com/spotify/fmt-maven-plugin#using-with-java-16-and-maven

Added file `.mvn/jvm.config` to my repository with contents:
```
--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED
```

**Comment by klaraward** [comment]
Readme updated in https://github.com/spotify/fmt-maven-plugin/pull/117

We intend to also add forking support to the plugin, so you can specify these flags in a better way, or preferably include them in the plugin itself. (If it's not fixed in [google-java-format](https://github.com/google/google-java-format/issues/612#issuecomment-915508862) before then)
